// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  buttons: {};
  common: {
    colorSchemes: {
      dark: "Dark Scheme";
      light: "Light Scheme";
    };
    englishFlag: "English flag";
    error: "error";
    georgianFlag: "Georgian flag";
    languages: {
      en: "English";
      ka: "Georgian";
    };
    loading: "Loading...";
  };
  errors: {};
  forms: {};
  home: {
    examples: "Examples";
    hero: {
      alt: "image, which is showcasing how site works";
      description: "You can easily share or bookmark URL link of the workout program";
      subtitle: "Create gym program and upon saving it, URLGegma will create hash of it";
      title: "URLGegma is a webapp for creating gym programs";
    };
    htmlTag: {
      description: "Gym program and workout plan builder";
      title: "URLGegma";
    };
  };
  navigation: {
    home: "Home";
    program: "Program";
  };
  program: {
    addExercise: "Add Exercise";
    copy: "Copy";
    copySuccess: "URL copied to clipboard";
    days: {
      friday: "Friday";
      monday: "Monday";
      newDay: "New Day";
      saturday: "Saturday";
      sunday: "Sunday";
      thursday: "Thursday";
      tuesday: "Tuesday";
      wednesday: "Wednesday";
    };
    programName: "Program Name";
    programSummary: "Program Summary";
    removeExercise: "Remove exercise";
    removeSet: "Remove set";
    reps: "Reps";
    restDay: "Rest Day";
    save: "Save";
    sets: "Sets";
    title: "Gym Program Builder";
    weight: "Weight (kg)";
  };
  validation: {};
}
