// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "adminDashboard": {
    "accounts_one": "{{count}} account",
    "accounts_other": "{{count}} accounts",
    "admin": "Admin",
    "allRoles": "All roles",
    "confirmDelete": "Confirm Delete",
    "confirmDeleteMessage": "Are you sure you want to delete this user?",
    "confirmRoleChange": "Confirm Role Change",
    "confirmRoleChangeMessage": "Are you sure you want to change role to {{role}}?",
    "createdAt": "Created",
    "email": "Email",
    "htmlTag": {
      "description": "Manage users and team accounts",
      "title": "Admin Dashboard - PataraURL"
    },
    "loadError": "Team data could not be loaded.",
    "member": "Member",
    "name": "Name",
    "next": "Next",
    "owner": "Owner",
    "previous": "Previous",
    "remove": "Remove user",
    "role": "Role",
    "updatedAt": "Updated"
  },
  "buttons": {

  },
  "common": {
    "cancel": "Cancel",
    "confirm": "Confirm",
    "error": "Error",
    "flag": {
      "englishFlag": "English flag",
      "georgianFlag": "Georgian flag"
    },
    "htmlTag": {
      "description": "An error occurred",
      "title": "Error - PataraURL"
    },
    "language": {
      "en": "English",
      "ka": "Georgian"
    },
    "loading": "Loading...",
    "mode": {
      "dark": "Dark Mode",
      "light": "Light Mode"
    },
    "websiteTitle": "PataraURL"
  },
  "errors": {

  },
  "forms": {

  },
  "home": {
    "htmlTag": {
      "description": "URL shortener",
      "title": "PataraURL - URL Shortener"
    },
    "productDescription": "URL Shortener"
  },
  "linksDashboard": {
    "actions": "Actions",
    "cancel": "Cancel",
    "close": "Close",
    "copied": "Copied to clipboard",
    "copy": "Copy",
    "createdAt": "Created",
    "delete": "Delete",
    "deleteConfirm": "Are you sure you want to delete this link?",
    "edit": "Edit",
    "hereWriteALink": "Here, type in the link",
    "htmlTag": {
      "description": "Manage your shortened links",
      "title": "Links Dashboard - PataraURL"
    },
    "loadError": "Failed to load links or perform action",
    "noLinks": "No shortened links yet",
    "save": "Save",
    "shortCode": "Short Code",
    "shortenButton": "Shorten",
    "stats": "Stats",
    "statsTitle": "Link Statistics",
    "title": "Links Dashboard",
    "totalAccesses": "Total Accesses",
    "urlRequired": "URL is required"
  },
  "login": {
    "accountCreated": "Account created. Login to continue.",
    "backHome": "Back home",
    "email": "Email",
    "htmlTag": {
      "description": "Login to your PataraURL account",
      "title": "Login - PataraURL"
    },
    "invalidCredentials": "Invalid email or password",
    "loginError": "Could not log you in",
    "loginTitle": "Login",
    "newHere": "New here?",
    "password": "Password",
    "registerLink": "Register"
  },
  "navigation": {
    "adminDashboard": "Admin Dashboard",
    "home": "Home",
    "links": "Links",
    "login": "Login",
    "logout": "Logout",
    "register": "Register"
  },
  "register": {
    "alreadyHaveAccount": "Already have an account? {{login}}",
    "createAccount": "Register",
    "createAccountError": "Could not create your account",
    "duplicateEmail": "An account with this email already exists",
    "email": "Email",
    "htmlTag": {
      "description": "Create a new PataraURL account",
      "title": "Register - PataraURL"
    },
    "loginLink": "Login",
    "name": "Name",
    "password": "Password",
    "registerTitle": "Register"
  },
  "validation": {
    "nameRequired": "Enter your name",
    "passwordMin": "Use at least 8 characters",
    "passwordRequired": "Enter your password",
    "validEmail": "Enter a valid email address"
  }
}
